### PR TITLE
Add OpenJDK8 changes and new performance page

### PR DESCRIPTION
**Pull request by SueChaplain**
Modifications to existing index and build page to
accommodate OpenJDK8 with OpenJ9(#33).

Addition of new Performance page(#26), necessitating
a better menu system (javascript builds the menu
per page now, which means all main pages are updated
with this).

Addition of new benchmark experiment for comparisons
when resources are constrained. Necessitates
changes to the Daytrader benchmark markdown file and
a new asset .png (chart).

Multiple issues addressed.

Updates/progress: #33
Closes: #26

Signed-off-by: Sue Chaplain <sue_chaplain@uk.ibm.com>

### CODE REVIEW

**Comment by doveye** [comment]
Jenkins website stage

**Comment by SueChaplain** [comment]
Jenkins website stage

**Comment by SueChaplain** [comment]
Jenkins website stage

**Comment by doveye** [comment]
Reviewed, looks ok to me

**Comment by SueChaplain** [comment]
Jenkins website stage

**Comment by SueChaplain** [comment]
Jenkins website stage

**Comment by SueChaplain** [comment]
Jenkins website stage

**Pull request merged**
