### PR TITLE
Restructure performance page

### PR DESCRIPTION
**Pull request by doveye**
Simplify performance page so that more info can be added without the page getting too long

[skip ci]

Signed-off-by: Esther Dovey <doveye@uk.ibm.com>

### CODE REVIEW

**Comment by doveye** [comment]
Jenkins website stage

**Comment by doveye** [comment]
Jenkins website stage

**Comment by doveye** [comment]
Jenkins website stage

**Comment by SueChaplain** [comment]
Jenkins website stage

**Comment by SueChaplain** [comment]
Looks good. Marius and Vijay are both good with the content, so merging this PR. Great work @doveye

**Pull request merged**
