### PR TITLE
Enable "wrap in quotes" by default for -Xtrace option builder tool

### PR DESCRIPTION
**Pull request by keithc-ca**
Fixes: #164

### CODE REVIEW

**Comment by pshipton** [comment]
@paulcheeseman can you please review this change.

**Comment by SueChaplain** [comment]
Before anyone merges this, @keithc-ca must make sure he has logged in to Eclipse Gerrit on his a/c. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=539831, which we're still trying to pursue for a resolution.

**Comment by keithc-ca** [comment]
@SueChaplain I logged in to https://git.eclipse.org/r/dashboard/self - is that you mean by 'Eclipse Gerrit'?
This PR is now showing 'All checks have passed'; what else needs to be done?

**Comment by SueChaplain** [comment]
That should do it @keithc-ca. 

@paulcheeseman have you reviewed this yet? Are you ok for me to merge please?

**Comment by paulcheeseman** [comment]
@keithc-ca

I deliberately chose not to enable this option by default because it causes problems when adding options for applications which don't launch the JVM via a shell, such as WAS.

**Comment by keithc-ca** [comment]
If you specify a filename, quotes are added either way: this just makes the result work in the presence of braces (`{` and `}`).

**Comment by paulcheeseman** [comment]
It's slightly more subtle than that. When "wrap in quotes" is disabled, quotes are automatically added around filenames because they can contain characters which would prevent the option from working correctly, regardless of whether it is used in a shell environment (e.g. spaces). For example:

`-Xtrace:none,maximal=mt,trigger=method{java/lang/String.<init>,jstacktrace},output="trace file.bin"`

When "wrap in quotes" is enabled the entire option is enclosed in quotes instead:

`"-Xtrace:none,maximal=mt,trigger=method{java/lang/String.<init>,jstacktrace},output=trace file.bin"`

The first version of the option will work with applications that launch the JVM via Runtime.exec() (like WAS) - but the second will not (the leading quote confuses the JVM). Conversely, the second one will work in a shell, but the first one will not.

I still think that the suggested patch represents a significant change in default behaviour that's sure to cause confusion for those who already use the tool for applications that do not launch the JVM via a shell - these users are unlikely to notice that they now need to uncheck the "wrap in quotes" option.

The issue was raised because one user didn't spot the "wrap in quotes" option, or didn't realise it was necessary - I just want to make sure that we don't overreact and cause more problems than we solve.  I wonder if showing a warning about the potential need to wrap in quotes might be a better solution. For example:

> WARNING: If this Xtrace option is going to be passed to the JVM via a shell, the "Wrap in quotes" option should be checked.

Also note that the Xdump Option Builder behaves in much the same way. So whatever changes we make to the Xtrace tool we need to mirror in the Xdump tool to keep them consistent.

**Comment by keithc-ca** [comment]
You note that quotes are needed in case the file name has spaces (they're added even if it does not).
The root of the issue is that, like spaces, braces are special and need to be quoted.
If quotes work for one problem they should work for the other; if quotes don't work, they won't solve either problem. If you're concerned that they're problematic in some context, then then should _only_ be added under control of the checkbox.

The `-Xdump` option uses `#` that will need quoting. I agree that the default there too should be to use quotes.

You're right that a user should be paying attention to the option to wrap in quotes, but that would include those that don't want them. In my opinion the primary benefit of these tools is the guidance through the complex structure of the options, not whether it's necessary to add or remove quotes.

**Comment by paulcheeseman** [comment]
> The root of the issue is that, like spaces, braces are special and need to be quoted.

Braces only need to be quoted when you're using the option in a shell.

But there are other characters which need to be quoted in **all** Xtrace option scenarios, regardless of whether you're using a shell. This is true for spaces (I think) and commas, which will confuse the JVM when it parses the Xtrace option if you don't quote them. I chose to simplify things by _always_ quoting filenames when "wrap in quotes" is unchecked, because this doesn't cause any negative side effects if the quotes aren't actually required.

> If you're concerned that they're problematic in some context, then then should only be added under control of the checkbox.

This approach would produce broken results when both of these things are true:

1. Filename contains a problematic character that needs to be quoted
2. JVM is not being launched via a shell

The "wrap in quotes (for use in a shell)" option doesn't simply enable/disable quotes - it formats the option for use in a shell, or not in a shell. I spent quite a bit of time making sure that both modes produce working results, and the current implementation is the simplest solution I found. (Things get even more interesting with Xdump options that use tool/exec commands containing quotes :o) )

It would be far more convenient if quoting the entire option worked in all scenarios, but the reality is that it doesn't. Quoting the entire option just doesn't work for non-shell use. I haven't dug too deeply into it but I would guess this is because the JVM doesn't recognise `"-Xtrace` as the beginning of an Xtrace option.

I think this boils down to a question of which scenario (shell or no shell) is more common. Certainly in my day job non-shell use is much more common, but I probably have a skewed view of things.

@pshipton do you have an opinion on this?

**Comment by keithc-ca** [comment]
A context where no quoting at all would be appropriate is in `eclipse.ini`.

**Comment by paulcheeseman** [comment]
> A context where no quoting at all would be appropriate is in `eclipse.ini`.

Wouldn't a comma in a filename still cause a problem there? I think at the very least you would lose the part of the filename after the comma.

`-Xtrace:none,maximal=j9vm,output=trace_1,000.bin`

When I tested just now this runs without any errors but you get a trace file called `trace_1`.

**Comment by keithc-ca** [comment]
> Wouldn't a comma in a filename still cause a problem there? I think at the very least you would lose the part of the filename after the comma.
> 
> `-Xtrace:none,maximal=j9vm,output=trace_1,000.bin`
> 
> When I tested just now this runs without any errors but you get a trace file called `trace_1`.

That's a feature of the parsing of the `-Xtrace` option: I don't think it supports commas within suboptions (and no quoting will help).

**Comment by paulcheeseman** [comment]
Wow, yes, you're right. Quoting doesn't help with a comma in the filename. That's something that needs to be added to the error-checking routines then (i.e. checking for commas).

I was convinced that there were scenarios where quotes were required around problematic characters in filenames and the Xdump tool's exec clause, even for non-shell scenarios when the option didn't need to be fully enclosed in quotes. But maybe I was mistaken and those quotes aren't needed after all. Certainly the results with eclipse.ini suggest that's the case. I'll look into this some more and try to remember how I was testing previously.

The original question of whether or not to enable the "wrap in quotes" option by default remains though. Clearly we disagree on that, so I'd like to get someone else's opinion (e.g. @pshipton).

**Comment by keithc-ca** [comment]
> Clearly we disagree

Well we agree on that point! ;-)

Peter will be unavailable for a couple days, but I think this can wait until he's had a chance to share his thoughts.

**Comment by DanHeidinga** [comment]
Does wrapping the individual suboptions in quotes achieve the same thing?
ie:  ```
-Xtrace:none,maximal=mt,trigger="method{java/lang/String.<init>,jstacktrace}",output="trace file.bin"
```
Note the quotes around the method spec.

> I think this boils down to a question of which scenario (shell or no shell) is more common.

Shell is definitely more common in the broader user base as there are many many more users running "java" vs a custom launcher.  We should default to enabling shell users.

**Comment by keithc-ca** [comment]
> Does wrapping the individual suboptions in quotes achieve the same thing?

Except in rare situations (e.g. a section that uses single-quotes around double-quotes) a single set of double-quotes has the same interpretation as quoting individual suboptions.

**Comment by DanHeidinga** [comment]
Does quoting the individual suboptions avoid the concern that `"-Xtrace:....` isn't recognized in `ini` or non-shell environments?

**Comment by keithc-ca** [comment]
I think in `eclipse.ini`, you would use no quotes at all; newlines separate arguments.
To my knowledge, the only special character there is `%` which introduces substitutions like `%u` for the user's name.

**Comment by paulcheeseman** [comment]
> I was convinced that there were scenarios where quotes were required around problematic characters in filenames and the Xdump tool's exec clause, even for non-shell scenarios when the option didn't need to be fully enclosed in quotes.

I'm pretty sure that WAS is the use-case I was considering here. In the WAS admin console JVM options are delimited by spaces (so strings with spaces need to be quoted), but the args are passed into ProcessBuilder/Runtime.exec() as-is so quoting the entire option causes it to fail (WAS fails to start IIRC).

https://www-01.ibm.com/support/docview.wss?uid=swg21417365#howto

> I think in eclipse.ini, you would use no quotes at all; newlines separate arguments.

Does quoting filenames or suboptions etc. actually cause problems for eclipse.ini? If not then I suggest we need to keep the non-shell mode as it is to avoid problems with WAS.

Or, even better, if Dan's idea of quoting suboptions works in _all_ scenarios we can do away with the "wrap in quotes" option altogether. It seems to work in the limited testing I've done so far, with an option like this:

`-Xtrace:none,maximal=mt,trigger="method{java/lang/String.<init>,jstacktrace}",output="{trace file.bin,10m}"`

Can you try this out please @keithc-ca?

**Comment by keithc-ca** [comment]
I expect your example will work from a shell, but not from `eclipse.ini`. I still think the 'wrap in quotes' option is useful, but I agree with Dan that the common case will be use with a shell.

**Comment by DanHeidinga** [comment]
> I expect your example will work from a shell, but not from eclipse.ini. 

Let's get that tested and confirm there's an issue before we drop the quote each segment approach.

**Comment by keithc-ca** [comment]
As suspected, `eclipse` does nothing with the quotes, the result being:
```
JVMTRCE003E Error processing trace option, detail: Trigger clause must end with '}'
JVMTRCE002E Error processing trace option: -Xtrace:trigger="method{java/lang/String.<init>,jstacktrace}"
```

**Comment by DanHeidinga** [comment]
Thanks for confirming @keithc-ca

**Comment by paulcheeseman** [comment]
> As suspected, `eclipse` does nothing with the quotes, the result being:
> 
> ```
> JVMTRCE003E Error processing trace option, detail: Trigger clause must end with '}'
> JVMTRCE002E Error processing trace option: -Xtrace:trigger="method{java/lang/String.<init>,jstacktrace}"
> ```

I managed to do some testing with WAS, and quoting the individual suboptions doesn't work there either - it leads to the same errors as you saw with eclipse.ini. I also tried it like this:

`-Xtrace:"trigger=method{java/lang/String.<init>,jstacktrace}"`

But that also doesn't work - it just fails silently - the JVM apparently ignores the `"trigger` suboption.

However, much to my surprise it turns out that quoting the entire option actually works fine with WAS. This is not what I remember from previous tests, but it may be that there was something else in those tests that prevented the quoted option from working (i.e. a space). Or maybe WAS has changed - it appears to be stripping off the leading/trailing quotes, but maybe it didn't do that before.

Also to my surprise, spaces in options cause problems for WAS _even when they're quoted_. I suspect the JVM option string from the Admin Console is split on spaces using a simple StringTokenizer, which would ignore the quotes. So the existing "non-shell" implementation doesn't work for WAS if the option contains a space, and I don't think there's any way to make it work.

The net of this is that I no longer have a problem with enabling "wrap in quotes" by default. I also agree that we should not quote filenames etc. when "wrap in quotes" is disabled. I'm happy to work on that aspect (and making the Xdump tool consistent) once this pull request has been merged.

**Comment by SueChaplain** [comment]
OK- merging now that we're all good with this :smile:

**Comment by paulcheeseman** [comment]
> The net of this is that I no longer have a problem with enabling "wrap in quotes" by default. I also agree that we should not quote filenames etc. when "wrap in quotes" is disabled. I'm happy to work on that aspect (and making the Xdump tool consistent) once this pull request has been merged.

See #166 for the additional items mentioned above.

**Pull request merged**
