### PR TITLE
OpenJDK11 quarkus performance results

### PR DESCRIPTION
**Pull request by Bazif-Khan**

### CODE REVIEW

**Comment by SueChaplain** [comment]
Jenkins website stage

**Comment by SueChaplain** [comment]
Jenkins website stage

**Comment by Bazif-Khan** [comment]
Jenkins website stage

**Comment by Bazif-Khan** [comment]
Jenkins website stage

**Comment by Bazif-Khan** [comment]
Jenkins website stage

**Comment by SueChaplain** [comment]
All tested on staging. LGTM

**Pull request merged**
