### PR TITLE
Add Whats new section for release 0.9.0

### PR DESCRIPTION
**Pull request by SueChaplain**
A few paragraphs of some of the key highlights
of the release and a pointer to more info.

Also calling out the Windows performance data
and addition of user documentation.

Closes: #81

Signed-off-by: Sue Chaplain <sue_chaplain@uk.ibm.com>

### CODE REVIEW

**Comment by SueChaplain** [comment]
Jenkins website stage

**Comment by SueChaplain** [comment]
Jenkins website stage

**Comment by SueChaplain** [comment]
Jenkins website stage

**Comment by SueChaplain** [comment]
Jenkins website stage

**Comment by SueChaplain** [comment]
@pshipton @DanHeidinga @mstoodle Pulled together a website update for 0.9.0. Is there anything here that you think I missed or you'd prefer I didn't mention. I don't want to repeat the What's new or Release notes, so just mentioned a couple of highlights.

View on the staging server: http://staging.eclipse.org/openj9/oj9_whatsnew.html

**Comment by pshipton** [comment]
> `and OpenJDK builds for applications that require Java heap sizes > 57 GB. Work is underway to make these builds available at AdoptOpenJDK `

Its not clear that only a xLinux large heap build is being made available at AdoptOpenJDK atm. For anything else you need to build your own.

> `we've run some performance tests to compare OpenJ9 and the Hotspot JVM. Our results indicate that OpenJ9 is 43% faster and uses 42% less memory.`

This is misleading, suggesting saying "some *Eclipse* performance tests"

Suggest adding a line for -XX:+UseNoGC

**Comment by SueChaplain** [comment]
Jenkins website stage

**Comment by SueChaplain** [comment]
sue_chaplain
Jenkins website stage

**Comment by DanHeidinga** [comment]
@SueChaplain Content looks good.  Can you confirm that the staggered view on the staging area won't be applied to the "real" page?

**Comment by SueChaplain** [comment]
Jenkins website stage

**Comment by SueChaplain** [comment]
@DanHeidinga Had a little trouble there with the staging job, but the page looks ok to me. Can you re-check please? I don't see any "staggering", so hopefully a browser issue or something.

**Comment by DanHeidinga** [comment]
I still see two columns with lots of white space in the staging area on Safari

**Comment by SueChaplain** [comment]
Jenkins website stage

**Comment by SueChaplain** [comment]
@DanHeidinga Found it eventually after reproducing with Safari. Problem was also there with Chrome, but only if you have a decent monitor (I don't!). Now fixed and tested.

**Comment by DanHeidinga** [comment]
Thanks @SueChaplain!  Looks good now

**Pull request merged**
