### PR TITLE
New Jenkins Pipeline for new website build

### PR DESCRIPTION
**Pull request by AdamBrousseau**
- Supports both Merge builds (push to master)
  and PR builds (push to staging).

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
Adam website stage

**Comment by AdamBrousseau** [comment]
adam website stage

**Comment by AdamBrousseau** [comment]
adam website stage

**Comment by SueChaplain** [comment]
@AdamBrousseau - please edit the `gatsby-config.js` file and change the line `pathPrefix: "/openj9-website",` (second from bottom line) to `pathPrefix: "/openj9",`

This change should fix all the paths and ensure that the links and images all work.

**Comment by AdamBrousseau** [comment]
adam website stage

**Comment by SueChaplain** [comment]
LGTM

**Pull request merged**
