### PR TITLE
Modify build page for OpenJDK V12

### PR DESCRIPTION
**Pull request by pmhayward**
Signed-off-by: Peter Hayward <pmhayward@uk.ibm.com>

### CODE REVIEW

**Comment by pmhayward** [comment]
Jenkins website stage

**Comment by pmhayward** [comment]
Jenkins website stage

**Comment by pmhayward** [comment]
Jenkins website stage

**Comment by pshipton** [comment]
Jenkins website stage

**Comment by SueChaplain** [comment]
Jenkins website stage

**Pull request merged**
