### PR TITLE
Add exit agent to xdump builder

### PR DESCRIPTION
**Pull request by theresa-m**
Related to: 
eclipse/openj9#7406
https://github.com/eclipse/openj9-docs/issues/414

Signed-off-by: Theresa Mammarella <Theresa.T.Mammarella@ibm.com>

### CODE REVIEW

**Comment by theresa-m** [comment]
Jenkins website stage

**Comment by SueChaplain** [comment]
@paulcheeseman - please can you take a look at this. If it's good, we need to coordinate the merge with work that is taking place to update the user docs for the next release (0.18.0) in January

**Comment by paulcheeseman** [comment]
@theresa-m 

Just a minor change on the tooltip - if we apply it to the `<li>` element which contains the new option it will appear when you hover anywhere over the checkbox or the label (not just when hovering over the checkbox):

```
@@ -110,7 +110,7 @@
        document.getElementById("range_li").title = titleText;

        titleText = "The exit agent is only supported from OpenJ9 release 0.18.0 and up.";
-       document.getElementById("agent_exit").title = titleText;
+       document.getElementById("agent_exit_li").title = titleText;
 }

 function parseParams() {
@@ -1439,7 +1439,7 @@
                                <input type="checkbox" id="agent_ceedump" name="agent" value="ceedump" onchange="process
Change(this)">
                                <label for="agent_ceedump">Generate an LE CEEDUMP dump (z/OS only)</label>
                        </li>
-                       <li>
+                       <li id="agent_exit_li">
                                <input type="checkbox" id="agent_exit" name="agent" value="exit" onchange="processChange
(this)">
                                <label for="agent_exit">Shutdown the JVM</label>
                        </li>
```

**Comment by theresa-m** [comment]
The openj9 change associated with this has been merged.

**Comment by SueChaplain** [comment]
@theresa-m - thanks for letting us know. We'll have to leave this PR open until 0.18.0 goes out as the pages are actually hosted at the website so will be live in when merged and won't match the release docs at Eclipse (as opposed to your openj9-docs changes, which will merge into the draft documentation in GitHub gh-pages).

**Comment by theresa-m** [comment]
> @theresa-m - thanks for letting us know. We'll have to leave this PR open until 0.18.0 goes out as the pages are actually hosted at the website so will be live in when merged and won't match the release docs at Eclipse (as opposed to your openj9-docs changes, which will merge into the draft documentation in GitHub gh-pages).

@SueChaplain I believe this is ready to be merged.

**Comment by SueChaplain** [comment]
@theresa-m - this is in hand. We'll be publishing docs and website PRs once OpenJDK 8 is available at Adopt.

**Pull request merged**
