### PR TITLE
Indicate where to download freemarker in the build instructions

### PR DESCRIPTION
**Pull request by DanHeidinga**
A user raised the question of where to get freemarker on slack today.  We should make the build instructions a little more obvious in that regards.  

Currently, the info is only in the docker file.

Signed-off-by: Dan Heidinga <daniel_heidinga@ca.ibm.com>

### CODE REVIEW

**Comment by DanHeidinga** [comment]
FYI @SueChaplain

**Comment by SueChaplain** [comment]
@DanHeidinga - Just looking at the v8 detailed build instructions now and I can't see where we are missing the information. Can you be more specific please and I can fix?

**Comment by DanHeidinga** [comment]
I think I'm missing something with respect to your question @SueChaplain. 

I added the missing content in this pull request - see the files changed tab: https://github.com/eclipse/openj9-website/pull/138/files

**Comment by SueChaplain** [comment]
Jenkins website stage

**Comment by SueChaplain** [comment]
Long day! I mistook this for an issue not a pull. 

Actually I don't think it is appropriate to put this content here. We are trying to make the build instructions on the website as easy looking as possible. This shortest/simplest process describes how to build using Docker, and freemarker is already included in the docker image.

Users wanting to build without docker are referred to the detailed build instructions, which show exactly where to get hold of freemarker. 

Disagree?

**Comment by DanHeidinga** [comment]
Our instructions on this page assume that the user knows where to get freemarker.  As it's the only required `configure` option, we should include a link for where to get it.

**Comment by SueChaplain** [comment]
But the process describes building with **Docker**, in which case you don't need to know where to get it, or any of the other build environment pre-reqs (compilers etc).

I'd actually like to remove everything from this page that is not essential (E.g. the verbose test section, which we can write up elsewhere) to get this down to the bare bones so that we illustrate just how easy it is to build an OpenJDK with OpenJ9. For any use case other than Docker, we have the detailed build instructions per platform.

**Comment by DanHeidinga** [comment]
As long as we require freemarker.jar, the minimal instructions should include where to get freemaker.  Similar to how we have a link to download docker on this page.

**Comment by DanHeidinga** [comment]
@SueChaplain Any further thoughts on this?

**Comment by doveye** [comment]
I guess the user missed the bit on the website where it says [Freemarker] "has already been installed into the Docker container". The user doesn't need to get it at all - the Docker container already has it.

Alternatively, if the user was trying to install using the build instructions at https://github.com/eclipse/openj9/blob/master/doc/build-instructions/Build_Instructions_V8.md, there are links or wget commands to take them straight to Freemarker.

**Comment by DanHeidinga** [comment]
Most users hitting this page aren't following the docker instructions.  If the point of this page is to 
>illustrate just how easy it is to build an OpenJDK with OpenJ9.

then we should include the minimum steps to successfully build which includes fetching freemarker

**Comment by doveye** [comment]
But the minimum steps include using the Docker image, which already has Freemarker. And the part of the website that would be changed by this PR is the instructions that use Docker, so if users aren't following the Docker instructions, they wouldn't be reading that bit anyway. 

The  PR change would lead to confusion because the content would basically say "you've got a Docker container, which includes Freemarker, and by the way, here's where you can get Freemarker"

**Comment by DanHeidinga** [comment]
Given the evidence that users are already confused with the current page (and I had to re-read it again to confirm), including the message that you can get freemarker from a link if you need to clarifies the build process.

**Comment by DanHeidinga** [comment]
I've read the page again and while it talks about building in the docker container, the steps are the same when building locally.  I suspect a lot of users looking to build assume they have the environment set up and just need the minimal steps of:
```
git clone https://github.com/ibmruntimes/openj9-openjdk-jdk8
cd openj9-openjdk-jdk8
bash ./get_source.sh
bash ./configure --with-freemarker-jar=/root/freemarker.jar
make all
```
Assuming that's the path they're on, the only missing info is where to get freemarker.jar from.  Providing that on this page makes it a pretty easy to follow recipe, especially for those who have already been able to build OpenJDK.

**Comment by SueChaplain** [comment]
Sorry for the delay responding ... been v busy!

I still have some usability concerns with the way this PR adds the information. Someone following the process to build an OpenJDK using Docker might well be puzzled by the link to obtain freemarker. 

*User: I thought I had everything I needed ... do I need to get this aswell?*

I am also concerned by the idea that a user might think they had the correct build environment already set up and just needed to do those 4 steps, because unless they are using Linux, the `configure` command requires more options.

If we really want to put an obvious link to freemarker on this page, I think we need to approach this differently. Re-purpose the page maybe? Since the requirement for this page came from @mstoodle, I think it is right that he should have a say.

The original requirement was to provide a fool-proof set of instructions to build an OpenJDK with OpenJ9 with the least possible steps. One suggestion to amend the `docker run` statement to map a drive (-v) so that the user could copy the built binary to their filesystem afterwards was turned down, because it added an unnecessary level of complexity.

If you have evidence that this page is persistently causing people to ask where they get freemarker (I only see 2 queries in slack), we should fix this somehow. At the very least I think this means adding some further text, probably at the top to outline the end to end process (including where you get freemarker), before providing the fool-proof method using Docker. This would undoubtedly extend the page. I'm not particularly in favour of this. Sometimes if you give people too much to read they lose interest.

Mark, please comment.

**Comment by mstoodle** [comment]
Maybe we could address this problem by adjusting this text:
```
If you don't want to use Docker or you want to build a binary for another platform,
read the full set of build instructions for JDK 8.
```

Can we move that text to look like the first step rather than the narrow column of text it currently appears as? Then maybe add a bit of explanation? "The Dockerfile you'll use in the instructions below creates the configuration that makes building OpenJDK with OpenJ9 very simple. If you don't want to use that Dockerfile, you'll need to replicate that configuration yourself. Please read the full set of build instructions to see what all you'll need and where to get it in the full set of build instructions for JDK 8."  

Do you think that would address the feedback we've received in the slack channel without gumming up the main instructions too much? @DanHeidinga @SueChaplain @doveye

**Comment by DanHeidinga** [comment]
That's a step forward.  I think we should also link to the detailed build instructions from the `Prepare your system` section so that it's clear that the steps below aren't sufficient outside docker.

**Comment by SueChaplain** [comment]
Thanks for your comments @DanHeidinga and @mstoodle. We'll get this planned in.

**Comment by SueChaplain** [comment]
Modifications made to the build page as part of https://github.com/eclipse/openj9-website/pull/157 to address concerns raised in this PR.

**Pull request closed without merging**
