### PR TITLE
Remove AdoptOpenJDK button from home page

### PR DESCRIPTION
**Pull request by davehobbs**
Signed-off-by: Dave Hobbs <dave_hobbs@uk.ibm.com>

### CODE REVIEW

**Comment by davehobbs** [comment]
Jenkins website stage

**Comment by AdamBrousseau** [comment]
What is the timeline for this change? Just hoping we don't have a gap between pushing this out and having the next solution in place.

**Comment by davehobbs** [comment]
Jenkins website stage

**Comment by SueChaplain** [comment]
LGTM

**Comment by SueChaplain** [comment]
For reference: 

Eclipse Foundation projects are not longer permitted to distribute, market or promote JDK binaries unless they have passed a Java SE Technology Compatibility Kit licensed from Oracle, to which the OpenJ9 project does not currently have access. See the [Eclipse Adoptium Project Charter](https://projects.eclipse.org/projects/adoptium/charter).

The mailing list reference is https://www.eclipse.org/lists/openj9-dev/msg00085.html

**Pull request merged**
