### PR TITLE
Replace buttons on build page with tabs and add instructions for v10

### PR DESCRIPTION
**Pull request by pmhayward**
Closes: #58 (build page buttons)
Closes: #50 (Bad formatting on IE)

Signed-off-by: Peter Hayward <pmhayward@uk.ibm.com>

### CODE REVIEW

**Comment by pmhayward** [comment]
Jenkins website stage

**Comment by SueChaplain** [comment]
Jenkins website stage

**Comment by AdamBrousseau** [comment]
Jenkins website stage

**Comment by SueChaplain** [comment]
Staged content looks good. Merging.

**Pull request merged**
