### PR TITLE
Restricting web intent

### PR DESCRIPTION
**Pull request by Bazif-Khan**
Ensuring cookie consent is obtained before tweets are made.

(Alternative method for adhering to GDPR regulations). 

Signed-off-by: Bazif Khan <bazif.khan@ibm.com>

### CODE REVIEW

**Comment by Bazif-Khan** [comment]
Jenkins website stage

**Comment by Bazif-Khan** [comment]
Jenkins website stage

**Comment by Bazif-Khan** [comment]
Jenkins website stage

**Comment by Bazif-Khan** [comment]
Jenkins website stage

**Comment by Bazif-Khan** [comment]
Jenkins website stage

**Comment by SueChaplain** [comment]
Closing. Twitter widget removed

**Pull request closed without merging**
