### PR TITLE
WIP: Create more hyperlinks in the front page

### PR DESCRIPTION
**Pull request by mstoodle**
This set of changes turns more of the text into appropriate links. In particular:
1) Make the main performance claims link to the performance data backing up the claim
2) Add a performance claim for our smoother rampup
3) Changes the "optimized for the cloud" claim to a link to the performance data page
4_ Makes the "Try it out..." text link to the appropriate download page.

Fixes: #115

### CODE REVIEW

**Comment by mstoodle** [comment]
jenkins website stage

**Comment by mstoodle** [comment]
ok, that didn't work very well. @SueChaplain is there another way I can test my changes?

**Comment by AdamBrousseau** [comment]
The build failed to clone the eclipse repo
```
 > git fetch --tags --progress ssh://genie.openj9@git.eclipse.org:29418/www.eclipse.org/openj9.git +refs/heads/*:refs/remotes/origin/*
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from ssh://genie.openj9@git.eclipse.org:29418/www.eclipse.org/openj9.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:888)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1155)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1186)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:113)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:85)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:75)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --progress ssh://genie.openj9@git.eclipse.org:29418/www.eclipse.org/openj9.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: No user exists for uid 11150
fatal: Could not read from remote repository.
```
Might need to open an Eclipse bugzilla for this.

**Comment by AdamBrousseau** [comment]
jenkins website stage

**Comment by AdamBrousseau** [comment]
Guess its an intermittent issue

**Comment by SueChaplain** [comment]
I'm just looking at staging now and I feel that there definitely are some UX issues here. The home page has so many links in the first half a page, as a user I'm not sure what to click first. 

The download button links to the releases page at Adopt, not the nightlies. Does that make the download button wrong please?

**Comment by mstoodle** [comment]
I think the button should go to the releases page, personally.

**Comment by mstoodle** [comment]
I created the issue based on design review of the web site, but I just sprayed all kinds of links. If they don't look good (I couldn't preview, so I was going to rely on the staging site to see what it looked like) then these changes should not be merged.

**Comment by mstoodle** [comment]
I've marked it WIP to make sure nobody merges :) .

**Comment by SueChaplain** [comment]
Implemented slightly differently in #121 for UX reasons.

**Pull request closed without merging**
